# Generated by Django 2.0.7 on 2018-12-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emf',
            name='event',
            field=models.CharField(choices=[('BR', 'Birthday'), ('WD', 'Wedding'), ('DW', 'DWedding'), ('AN', 'Anniversary'), ('FS', 'Festive'), ('SP', 'Special')], default='BR', max_length=2),
        ),
        migrations.AlterField(
            model_name='emf',
            name='events',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
