# Generated by Django 2.0.7 on 2018-12-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0002_auto_20181205_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emf',
            name='events',
            field=models.CharField(blank=True, default='Birthday,Wedding,Destnation Wedding, Anniverary,Festive Party,Special', max_length=120),
        ),
    ]
