# Generated by Django 2.0.7 on 2018-12-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0003_auto_20181205_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='emf',
            name='specialty',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
