# Generated by Django 2.0.7 on 2018-12-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0004_emf_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emf',
            name='specialty',
            field=models.CharField(default='Wedding', max_length=20),
        ),
    ]
