# Generated by Django 2.0.7 on 2018-12-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0005_auto_20181206_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emf',
            name='specialty',
            field=models.CharField(default='', max_length=20),
        ),
    ]
